# Generated by Django 3.2 on 2022-03-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_pic', models.ImageField(blank=True, upload_to='post_preview_pics')),
                ('title', models.CharField(max_length=64)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ['pk'],
            },
        ),
    ]
